captainVersion: 4
services:
    $$cap_appname-db:
        image: mariadb:$$cap_db_version
        environment:
            MYSQL_ROOT_PASSWORD: $$cap_db_root_password
            MYSQL_USER: $$cap_db_username
            MYSQL_PASSWORD: $$cap_db_root_password
            MYSQL_DATABASE: $$cap_db_database
        volumes:
            - $$cap_appname-db:/var/lib/mysql
        caproverExtra:
            notExposeAsWebApp: 'true'
            dockerfileLines:
                - CMD [ mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin ]

    $$cap_appname-app:
        image: linkace/linkace:$$cap_app_version
        environment:
            DB_CONNECTION: mysql
            DB_HOST: srv-captain--$$cap_appname-db
            DB_PORT: 3306
            DB_DATABASE: $$cap_db_database
            DB_USERNAME: $$cap_db_username
            DB_PASSWORD: $$cap_db_root_password
            APP_KEY: 'base64:XWf7nDXlxQcsqyAl4wp3FoIfDP9jxkbJoD4fynzac1k='
        depends_on:
            - $$cap_appname-db
        caproverExtra:
            containerHttpPort: '80'

caproverOneClickApp:
    variables:
        - id: $$cap_db_root_password
          label: 'Database Password'
          description: 'Enter the password for database root.'
          defaultValue: 'linkace'
          validRegex: /.{1,}/
        - id: $$cap_db_username
          label: 'Database Username'
          description: 'Enter the username for the database.'
          defaultValue: 'linkace'
          validRegex: /.{1,}/
        - id: $$cap_db_database
          label: 'Database Name'
          description: 'Enter the name of the database.'
          defaultValue: 'linkace'
          validRegex: /.{1,}/
        - id: $$cap_db_version
          label: 'Database Name'
          description: 'The tags and versions can be found at https://hub.docker.com/_/mariadb/tags'
          defaultValue: '10.7'
          validRegex: /.{1,}/
        - id: $$cap_app_version
          label: 'App docker tag'
          description: 'The tags and versions can be found at https://hub.docker.com/r/linkace/linkace/tags'
          defaultValue: 'simple'
          validRegex: /.{1,}/

    instructions:
        start: |-
            The LinkAce app is a web-based bookmarking application. It provides a convenient way to save and organize your bookmarks.
            GitHub: https://github.com/Kovah/LinkAce

        end: |-
            !!!!!!!!! IMPORTANT TO READ !!!!!!!!!!!
            Because of how LinkAce works, you have to run the following command before you continue with the installation.

            docker exec <container name> chmod 777 .env

            After that you can continue with your setup at: http://$$cap_appname.$$cap_root_domain/ .
            Enjoy! Selfhosted.club 😉

    displayName: 'LinkAce'
    isOfficial: false
    description: 'Web-based bookmarking application.'
    documentation: https://github.com/LinkAce2/LinkAce
